version: 2.1

orbs:
  docker: circleci/docker@2.0.3

executors:
  go-linux:
    resource_class: medium
    docker:
      - image: docker.mirror.hashicorp.services/golang:1.20
    shell: /usr/bin/env bash -euo pipefail -c
    environment:
      GO111MODULE: "on"
      HCLOUD_ENDPOINT: http://localhost:3000/v1
    working_directory: /go/src/github.com/AndrewChubatiuk/nomad-hcloud-autoscaler

jobs:
  check-deps-go:
    executor: go-linux
    steps:
      - checkout
      - run: make check

  lint-go:
    executor: go-linux
    steps:
      - checkout
      - run: make lint-tools
      - run: make lint

  linux-build-go:
    executor: go-linux
    steps:
      - checkout
      - run: make build
      - persist_to_workspace:
          root: ./bin/
          paths:
            - "*"

  linux-test-go:
    executor: go-linux
    docker:
      - image: docker.mirror.hashicorp.services/golang:1.20
      - image: mockoon/cli:latest
        command: -d https://raw.githubusercontent.com/mockoon/mock-samples/main/mock-apis/data/hetznercloud.json --port 3000
    steps:
      - checkout
      - run: make test-tools
      - run: make test

  release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./bin/
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./bin/

workflows:
  ci:
    jobs:
      - check-deps-go:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - lint-go:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - linux-build-go:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - linux-test-go:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - docker/publish:
          attach-at: ./bin/
          deploy: true
          image: achubatiuk/nomad-autoscaler
          tag: $CIRCLE_BRANCH
          requires:
            - check-deps-go
            - lint-go
            - linux-build-go
            - linux-test-go
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - release:
          requires:
            - check-deps-go
            - lint-go
            - linux-build-go
            - linux-test-go
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
